#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Haymans"
  https://create.arduino.cc/cloud/things/40ce5c6e-c86c-4a3c-a052-72b0294d4348 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight lightSwitch;
  int sensor;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

//setup variables
int lightSensorPin = A0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  //set ledpins as output
  //pinMode(blueled, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  //read light sensor value
  sensor = analogRead(lightSensorPin);
  Serial.println(sensor);
  delay(5000);
}

/*
  Since LightSwitch is READ_WRITE variable, onLightSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightSwitchChange()  {
  // Add your code here to act upon LightSwitch change
  
  //write on/off status from dashboard to led
  //analogWrite(blueled,lightSwitch);
}

/*if(sensor >= 400){
    Serial.print("on\n");
    //analogWrite(blueled,1);
  } else if (sensor < 400){
    Serial.print("off\n");
    //analogWrite(blueled,0);
  }*/










