// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTimeCloseChange();
void onTimeOpenChange();

bool curtainStatus;
CloudTime timeClose;
CloudTime timeNow;
CloudTime timeOpen;
CloudTime time_read;

void initProperties(){

  ArduinoCloud.addProperty(curtainStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timeClose, READWRITE, ON_CHANGE, onTimeCloseChange);
  ArduinoCloud.addProperty(timeNow, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timeOpen, READWRITE, ON_CHANGE, onTimeOpenChange);
  ArduinoCloud.addProperty(time_read, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
